$drawablePath = "C:\Users\Administrator\AndroidStudioProjects\intprogXml\app\src\main\res\drawable"
Rename-Item "$drawablePath\Centrum Advance 100s.jpg" "centrum_advance_100s.jpg"
Rename-Item "$drawablePath\Coca-Cola Zero 1.5L.jpg" "coca_cola_zero_1_5l.jpg"
Rename-Item "$drawablePath\Corona Extra 355mL x 6.jpg" "corona_extra_355ml_x_6.jpg"
Rename-Item "$drawablePath\Del Monte Pineapple Juice 1.36L.webp" "del_monte_pineapple_juice_1_36l.webp"
Rename-Item "$drawablePath\Dyson V12 Detect Slim.png" "dyson_v12_detect_slim.png"
Rename-Item "$drawablePath\Heinz Tomato Ketchup 1.25kg.jpg" "heinz_tomato_ketchup_1_25kg.jpg"
Rename-Item "$drawablePath\Hershey's Crunch Choco Monaka.jpg" "hersheys_crunch_choco_monaka.jpg"
Rename-Item "$drawablePath\Johnnie Walker Black Label 1L.jpg" "johnnie_walker_black_label_1l.jpg"
Rename-Item "$drawablePath\Kirkland Almond Butter 765g.jpg" "kirkland_almond_butter_765g.jpg"
Rename-Item "$drawablePath\Kirkland Bath Tissue 30 rolls.jpg" "kirkland_bath_tissue_30_rolls.jpg"
Rename-Item "$drawablePath\L'Oreal Paris Revitalift Serum.png" "loreal_paris_revitalift_serum.png"
Rename-Item "$drawablePath\Lysol Disinfectant Spray.webp" "lysol_disinfectant_spray.webp"
Rename-Item "$drawablePath\Magnum Almond White.jpg" "magnum_almond_white.jpg"
Rename-Item "$drawablePath\Meiji Ess Cup Mini.jpg" "meiji_ess_cup_mini.jpg"
Rename-Item "$drawablePath\Moet & Chandon Brut Imperial.jpg" "moet_chandon_brut_imperial.jpg"
Rename-Item "$drawablePath\Nestle Vanilla Cone 6pcs.jpg" "nestle_vanilla_cone_6pcs.jpg"
Rename-Item "$drawablePath\Nissin Cup Noodles Seafood 5s.jpg" "nissin_cup_noodles_seafood_5s.jpg"
Rename-Item "$drawablePath\Quaker Oats Old Fashioned 1.2kg.jpg" "quaker_oats_old_fashioned_1_2kg.jpg"
Rename-Item "$drawablePath\Samsung 55 Crystal UHD 4K TV.jpg" "samsung_55_crystal_uhd_4k_tv.jpg"
Rename-Item "$drawablePath\Selecta Double Dutch 1.5L.avif" "selecta_double_dutch_1_5l.avif"
Rename-Item "$drawablePath\Seoju Melon Bar 8 x 75mL.jpg" "seoju_melon_bar_8_x_75ml.jpg"
